/*
 * This file is generated by jOOQ.
*/
package com.mashuq.athenaeum.domain.athenaeum;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import com.mashuq.athenaeum.domain.DefaultCatalog;
import com.mashuq.athenaeum.domain.athenaeum.tables.Book;
import com.mashuq.athenaeum.domain.athenaeum.tables.Information;
import com.mashuq.athenaeum.domain.athenaeum.tables.Request;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = {"http://www.jooq.org",
		"jOOQ version:3.10.5"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Athenaeum extends SchemaImpl {

	private static final long serialVersionUID = 16822111;

	/**
	 * The reference instance of <code>ATHENAEUM</code>
	 */
	public static final Athenaeum ATHENAEUM = new Athenaeum();

	/**
	 * The table <code>ATHENAEUM.BOOK</code>.
	 */
	public final Book BOOK = com.mashuq.athenaeum.domain.athenaeum.tables.Book.BOOK;

	/**
	 * The table <code>ATHENAEUM.INFORMATION</code>.
	 */
	public final Information INFORMATION = com.mashuq.athenaeum.domain.athenaeum.tables.Information.INFORMATION;

	/**
	 * The table <code>ATHENAEUM.REQUEST</code>.
	 */
	public final Request REQUEST = com.mashuq.athenaeum.domain.athenaeum.tables.Request.REQUEST;

	/**
	 * No further instances allowed
	 */
	private Athenaeum() {
		super("ATHENAEUM", null);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Catalog getCatalog() {
		return DefaultCatalog.DEFAULT_CATALOG;
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(Book.BOOK, Information.INFORMATION,
				Request.REQUEST);
	}
}
