/*
 * This file is generated by jOOQ.
*/
package com.mashuq.athenaeum.domain.athenaeum;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import com.mashuq.athenaeum.domain.athenaeum.tables.Book;
import com.mashuq.athenaeum.domain.athenaeum.tables.Information;
import com.mashuq.athenaeum.domain.athenaeum.tables.Request;

/**
 * A class modelling indexes of tables of the <code>ATHENAEUM</code> schema.
 */
@Generated(value = {"http://www.jooq.org",
		"jOOQ version:3.10.5"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

	// -------------------------------------------------------------------------
	// INDEX definitions
	// -------------------------------------------------------------------------

	public static final Index PRIMARY_KEY_1 = Indexes0.PRIMARY_KEY_1;
	public static final Index CONSTRAINT_INDEX_F = Indexes0.CONSTRAINT_INDEX_F;
	public static final Index PRIMARY_KEY_F = Indexes0.PRIMARY_KEY_F;
	public static final Index CONSTRAINT_INDEX_6 = Indexes0.CONSTRAINT_INDEX_6;
	public static final Index PRIMARY_KEY_6 = Indexes0.PRIMARY_KEY_6;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Indexes0 {
		public static Index PRIMARY_KEY_1 = Internal.createIndex(
				"PRIMARY_KEY_1", Book.BOOK, new OrderField[]{Book.BOOK.BOOKID},
				true);
		public static Index CONSTRAINT_INDEX_F = Internal.createIndex(
				"CONSTRAINT_INDEX_F", Information.INFORMATION,
				new OrderField[]{Information.INFORMATION.REQUESTID}, false);
		public static Index PRIMARY_KEY_F = Internal.createIndex(
				"PRIMARY_KEY_F", Information.INFORMATION,
				new OrderField[]{Information.INFORMATION.INFORMATIONID}, true);
		public static Index CONSTRAINT_INDEX_6 = Internal.createIndex(
				"CONSTRAINT_INDEX_6", Request.REQUEST,
				new OrderField[]{Request.REQUEST.BOOKID}, false);
		public static Index PRIMARY_KEY_6 = Internal.createIndex(
				"PRIMARY_KEY_6", Request.REQUEST,
				new OrderField[]{Request.REQUEST.REQUESTID}, true);
	}
}
