/*
 * This file is generated by jOOQ.
*/
package com.mashuq.athenaeum.domain.athenaeum;


import com.mashuq.athenaeum.domain.athenaeum.tables.Book;
import com.mashuq.athenaeum.domain.athenaeum.tables.Bookinformationrequest;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ATHENAEUM
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ATHENAEUM.BOOK</code>.
     */
    public static final Book BOOK = com.mashuq.athenaeum.domain.athenaeum.tables.Book.BOOK;

    /**
     * The table <code>ATHENAEUM.BOOKINFORMATIONREQUEST</code>.
     */
    public static final Bookinformationrequest BOOKINFORMATIONREQUEST = com.mashuq.athenaeum.domain.athenaeum.tables.Bookinformationrequest.BOOKINFORMATIONREQUEST;
}
