CREATE TABLE ATHENAEUM.Book (
  BookID INT NOT NULL AUTO_INCREMENT,
  Title VARCHAR(4000) NOT NULL,
  SubTitle VARCHAR(4000) NULL,
  ISBN10 VARCHAR(512) NULL,
  ISBN13 VARCHAR(512) NULL,
  indexed TINYINT(1),
  PRIMARY KEY (BookID));
