CREATE TABLE ATHENAEUM.Book (
  BookID INT NOT NULL AUTO_INCREMENT,
  Title VARCHAR(4000) NOT NULL,
  SubTitle VARCHAR(4000) NULL,
  ISBN10 VARCHAR(512) NULL,
  ISBN13 VARCHAR(512) NULL,
  indexed TINYINT(1),
  PRIMARY KEY (BookID));
  
  
CREATE TABLE ATHENAEUM.Request (
  RequestID INT NOT NULL AUTO_INCREMENT,
  BookID INT NOT NULL UNIQUE, 
  Status VARCHAR(20) NOT NULL,
  FOREIGN KEY (BookID) REFERENCES Book(BookID),
  PRIMARY KEY (RequestID)); 
  
  
CREATE TABLE ATHENAEUM.Information (
  InformationID INT NOT NULL AUTO_INCREMENT,
  RequestID INT NOT NULL, 
  Reference VARCHAR(64) NOT NULL,
  Status VARCHAR(20) NOT NULL,
  Data VARCHAR(128) NULL, 
  FOREIGN KEY (RequestID) REFERENCES Request(RequestID),
  PRIMARY KEY (InformationID));    
