/*
 * This file is generated by jOOQ.
*/
package com.mashuq.athenaeum.domain;


import com.mashuq.athenaeum.domain.tables.Book;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.BOOK</code>.
     */
    public static final Book BOOK = com.mashuq.athenaeum.domain.tables.Book.BOOK;
}
