/*
 * This file is generated by jOOQ.
*/
package com.mashuq.athenaeum.domain.athenaeum.tables.records;


import com.mashuq.athenaeum.domain.athenaeum.tables.Bookinformationrequest;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookinformationrequestRecord extends TableRecordImpl<BookinformationrequestRecord> implements Record4<Integer, Integer, Integer, String> {

    private static final long serialVersionUID = -621210023;

    /**
     * Setter for <code>ATHENAEUM.BOOKINFORMATIONREQUEST.BOOKREQUESTID</code>.
     */
    public void setBookrequestid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ATHENAEUM.BOOKINFORMATIONREQUEST.BOOKREQUESTID</code>.
     */
    public Integer getBookrequestid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ATHENAEUM.BOOKINFORMATIONREQUEST.BOOKID</code>.
     */
    public void setBookid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>ATHENAEUM.BOOKINFORMATIONREQUEST.BOOKID</code>.
     */
    public Integer getBookid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ATHENAEUM.BOOKINFORMATIONREQUEST.REQUESTSTATUS</code>.
     */
    public void setRequeststatus(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>ATHENAEUM.BOOKINFORMATIONREQUEST.REQUESTSTATUS</code>.
     */
    public Integer getRequeststatus() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>ATHENAEUM.BOOKINFORMATIONREQUEST.REQUESTEREMAIL</code>.
     */
    public void setRequesteremail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ATHENAEUM.BOOKINFORMATIONREQUEST.REQUESTEREMAIL</code>.
     */
    public String getRequesteremail() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Bookinformationrequest.BOOKINFORMATIONREQUEST.BOOKREQUESTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Bookinformationrequest.BOOKINFORMATIONREQUEST.BOOKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Bookinformationrequest.BOOKINFORMATIONREQUEST.REQUESTSTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Bookinformationrequest.BOOKINFORMATIONREQUEST.REQUESTEREMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getBookrequestid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getBookid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRequeststatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRequesteremail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBookrequestid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getBookid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRequeststatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRequesteremail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookinformationrequestRecord value1(Integer value) {
        setBookrequestid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookinformationrequestRecord value2(Integer value) {
        setBookid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookinformationrequestRecord value3(Integer value) {
        setRequeststatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookinformationrequestRecord value4(String value) {
        setRequesteremail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookinformationrequestRecord values(Integer value1, Integer value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookinformationrequestRecord
     */
    public BookinformationrequestRecord() {
        super(Bookinformationrequest.BOOKINFORMATIONREQUEST);
    }

    /**
     * Create a detached, initialised BookinformationrequestRecord
     */
    public BookinformationrequestRecord(Integer bookrequestid, Integer bookid, Integer requeststatus, String requesteremail) {
        super(Bookinformationrequest.BOOKINFORMATIONREQUEST);

        set(0, bookrequestid);
        set(1, bookid);
        set(2, requeststatus);
        set(3, requesteremail);
    }
}
